query ProductsPage($first: Int!, $skip: Int!, $orderBy: ProductOrderByInput) {
	products: productsConnection(first: $first, skip: $skip, orderBy: $orderBy) {
		aggregate {
			...Aggregate
		}
		edges {
			node {
				...ProductBase
			}
		}
		pageInfo {
			...PageInfo
		}
	}
}
